### PR TITLE
find root

### LINKED ISSUE #282: JsPrettier doesn't run in appropriate context when used in monorepo context
### Context: 

Complex monorepo with the following structure 

```
/root
    /libs
    /apps
        /app1
            /packages 
                /pkg1
                ...
```

Some of the apps are implemented using `Svelte` and some of the apps have a workspace structure with some of the packages using `Svelte`. 

The SublimeText has the `root` added to the project and various internal folders. 

When attempting to format the file, JsPrettier sometimes executes in the wrong context. This results in errors related to finding the appropriate plugins (in my case `prettier-plugin-svelte`). 

### Solution

I created a small function that finds the first ancestor of the file that has a `package.json` and uses that as the `CWD` for prettier. I then use `find_root` instead of `get_st_project_path` in [run](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L227).

```
from pathlib import Path
def find_root(source_file_path):
    for p in Path(source_file_path).parents:
        if "package.json" in os.listdir(p):
            return p

    return None
```

I switched to the provided `python 3.8` on my local version in order to have access to `pathlib`but I guess a backwards compatible version can be created for ST2. 

ST: 4169
JsPrettier: 1.65.4
MacOS: 14.4.1 (23E224)

### PR DESCRIPTION
**Pull request by pdamoc**
This solution is python2 compatible and works in python3 as well.

closes #282

### CODE REVIEW

**Comment by pdamoc** [comment]
I just realized that the run fails if the file is not inside a project. I will fix it as soon as I have some time.

**Comment by jonlabelle** [comment]
@pdamoc: This is going to take a bit more testing. What happens if you don't have a `package.json` file, e.g. you're using global prettier. `get_st_project_path` is also used [similar decision making](https://github.com/search?q=repo%3Ajonlabelle/SublimeJsPrettier%20get_st_project_path&type=code) scenarios.

**Comment by jonlabelle** [comment]
@pdamoc: Can you attach a minimal project (zipped) that reproduces the behavior, and so I can run on my end?

**Comment by pdamoc** [comment]
Here you go:
[mono.zip](https://github.com/jonlabelle/SublimeJsPrettier/files/15137582/mono.zip)

Open `mono` folder in Sublime. Go to  `mono\apps\app1\src\Main.svelte`.

Run JsPrettier. It should fail with an error like: 

`mono/apps/app1/src/Main.svelte: Error: Cannot find package 'prettier-plugin-svelte' imported from `

The `find_root` version should succeed.

**Comment by jonlabelle** [comment]
@pdamoc:  Worked perfect for me, err... no errors.

Here's the debug output:

```console
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command
-----------------------------------------

/Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/node_modules/.bin/prettier \
    --config /Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/package.json \
    --parser html \
    --use-tabs false \
    --stdin-filepath /Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/src/Main.svelte \
    --log-level debug
```

### Prettier produced the following output:

```json
{
  "": [],
  "cache": false,
  "color": true,
  "editorconfig": true,
  "useTabs": false,
  "config": "/Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/package.json",
  "parser": "html",
  "filepath": "/Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/src/Main.svelte",
  "logLevel": "debug",
  "configPrecedence": "cli-override",
  "debugRepeat": 0,
  "ignorePath": [".gitignore", ".prettierignore"],
  "plugins": [],
  "_": [],
  "__raw": {
    "_": [],
    "cache": false,
    "color": true,
    "editorconfig": true,
    "use-tabs": false,
    "config": "/Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/package.json",
    "parser": "html",
    "stdin-filepath": "/Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/src/Main.svelte",
    "log-level": "debug",
    "config-precedence": "cli-override",
    "debug-repeat": 0,
    "ignore-path": [".gitignore", ".prettierignore"],
    "plugin": []
  }
}

// [debug] load config file from
// '/Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/package.json'

// [debug] loaded options
{
  "useTabs": false,
  "singleQuote": false,
  "trailingComma": "none",
  "printWidth": 100,
  "tabWidth": 4,
  "htmlWhitespaceSensitivity": "ignore",
  "bracketSameLine": true,
  "plugins": ["prettier-plugin-svelte"],
  "parser": "svelte"
}

// [debug] applied config-precedence (cli-override):
{
  "filepath": "/Users/jon/tmp/jsprettier-mono-repo-283/apps/app1/src/Main.svelte",
  "singleQuote": false,
  "bracketSameLine": true,
  "htmlWhitespaceSensitivity": "ignore",
  "trailingComma": "none",
  "parser": "html",
  "plugins": ["prettier-plugin-svelte"],
  "printWidth": 100,
  "tabWidth": 4,
  "useTabs": false
}
```

```console
Prettier process finished with exit code 0.
```

**Comment by pdamoc** [comment]
Ok, it appear to be an issue on my side (config). Feel free to close both the issue and the PR. 

The errors stopped when I removed `"prettier_cli_path":"/Users/peter/.asdf/shims/prettier",` from the settings.  I had a global install of prettier and this interfered in a way that was fixed by the `find_root` changes.

**Pull request closed without merging**
