### PR TITLE
Json

### PR DESCRIPTION
**Pull request by PatrickRoumanoff**
finishing up on #47 
internally override the 'trailingComma' for json and set the value to 'none'

### CODE REVIEW

**Comment by jonlabelle** [comment]
I'm not sure the `trailingComma` option is being currently being adhered to; at least when I toggle it running Prettier v1.5.2.

When I formatted a JSON file with `"trailingComma": "none"`, the trailing comma was still not removed, and Prettier threw an error...

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/local/bin/prettier --stdin --print-width 80 --single-quote=true --trailing-comma none --bracket-spacing=true --jsx-bracket-same-line=false --parser json --semi=true --tab-width 2 --use-tabs=false

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error:

stdin: SyntaxError: (json-to-ast) Unexpected token <}> at (14:1)
  12 |   "eqnull": true,
  13 |   "node": true,
> 14 | }
     | ^
  15 | 

Process finished with exit code 2
```

**Contents of Target JSON file *before* format:**

```json
{
  "test_trailing_comma": ["1", "2", "2",]
}
```

**Contents of Target JSON file *after* format:**

```json
{
  "test_trailing_comma": ["1", "2", "2",]
}
```

e.g.: No formatting was applied.

**Comment by PatrickRoumanoff** [comment]
If the file is invalid prettier will throw an error. This is standard
behaviour.
A json file with trailing coma is invalid and prettier will reject it.

The issue here is that prettier will still honor the trailing coma option
with json parser enabled. And this pr is about making sure this option is
turned off when formatting json files. Otherwise prettier will transform A
valid json file into an invalid one.

**Comment by jonlabelle** [comment]
Maybe I'm misunderstanding... but the behavior of setting/changing the option seems to be irrelevant since it's not adhered to.

**Comment by PatrickRoumanoff** [comment]
Afaik calling --parser json --trailing-comma es5 will render the json
invalid

**Comment by PatrickRoumanoff** [comment]
this is exactly what I am talking about: https://github.com/prettier/prettier/issues/2308
so this is fixed in prettier, but not yet released.

**Comment by jonlabelle** [comment]
I'll close the PR since it's an external issue.

**Comment by PatrickRoumanoff** [comment]
yes but until this is fixed in prettier, it will break json files

**Pull request closed without merging**
