### PR TITLE
#47 add support for json

### PR DESCRIPTION
**Pull request by PatrickRoumanoff**
Not too sure what I am doing, but this seems to work for me
implementation for #47

### CODE REVIEW

**Comment by sidati** [comment]
Not working

**Comment by PatrickRoumanoff** [comment]
I have issues as well. I think we need to override `--trailing-comma none` for json mode otherwise prettier will add unwanted comma

**Comment by sidati** [comment]
image

**Comment by PatrickRoumanoff** [comment]
@sidati what is your prettier version? the json parser is a recent addition.

**Comment by sidati** [comment]
Hi @PatrickRoumanoff, prettier@1.4.4

**Comment by sidati** [comment]
You're right 👍
Its my **outdated** prettier

**Pull request merged**
