### PR TITLE
Improved performance by caching prettier config path

### PR DESCRIPTION
**Pull request by gornostal**
Hi,
This PR improves performance by 40%.
I noticed that it took a lot of time to find .prettierrc using shell command.
Although I have an SSD it took around 0.25-0.4 seconds, which is really noticeable when you user prettier on file save.

### CODE REVIEW

**Comment by jonlabelle** [comment]
Build seems to be failing.

**Comment by gornostal** [comment]
Could you look into the look please?
It looks like a configuration error. Sonar-scanner not found.
Tests are passing though.

**Comment by jonlabelle** [comment]
Here's the error... 

```
+echo -n '> Run pylint'
> Run pylint+pylint JsPrettier.py
************* Module JsPrettier
E: 10, 0: No name 'lru_cache' in module 'functools' (no-name-in-module)
```

**Comment by gornostal** [comment]
Do you support ST2?
Python2 doesn't have `lru_cache` built in.

**Comment by jonlabelle** [comment]
Yes.. both [ST2 and ST3 and all Platforms](https://github.com/jonlabelle/SublimeJsPrettier#installation).

**Comment by gornostal** [comment]
I fixed the error, but the build still fails.
```
sonar-scanner: command not found
```
What can I do?

**Comment by jonlabelle** [comment]
Thanks for the PR @gornostal!

**Comment by jonlabelle** [comment]
I need to revert this PR... here's the error in ST2

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\JsPrettier.py", line 17, in <module>
    from JsPrettier.cache import lru_cache
ImportError: No module named cache
```

**Comment by gornostal** [comment]
> I need to revert this PR... here's the error in ST2

I'll fix that later this week

**Comment by jonlabelle** [comment]
Also... please source and include CR info (if applicable) from the code you are using for the back-port. It looks awful similar to [jaraco/backports.functools_lru_cache](https://github.com/jaraco/backports.functools_lru_cache/blob/master/backports/functools_lru_cache.py).

**Comment by gornostal** [comment]
What is CR info? :)

**Comment by gornostal** [comment]
ah, Copyright.
OK

**Pull request merged**
