### PR TITLE
Adding typescript-babel-parser option

### PR DESCRIPTION
**Pull request by rockerBOO**
I currently use experimental features in babel (pipeline operator) and the typescript parser doesn't use the babel options. 

[parser: babel](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKBLAtgBwgJxgAJgiA1OMGAgGiIEMATRuxjANw0bjoGcBXAEYx89KnSz8ANjAw4pATyIBfIgDN8ELEQDkAOgD07StXw702PIRJEp2DMVUatuwwCZG5qBdwFipLHocOnw4Rn4wOBV1TW0dfihufF5IUK90dDgADytiSChePIgACzheDGhUGABeIgAKNQJIpHITAgBKImqAPnrG-EjeFooqAgBtAF1OnoyRMIi4BqayuiYWIgAGdtmAH162Tm46qQQAcxhizoMDIgOuKMElC6jqGHopIih+LEE4fCIIGp1MteBkoCAaCAIDhZNBeMhQPR8JoAO4ABSRCHhKHo7AgXAhIEEojAAGs4DAAMo4MQYKCnZAifg8EDFGBYKQAdWKDjKNMilKxDg4DgUyHAvHhkLpvD+MDRolOgWQanesshACteFkAEIk8lU+hYOAAGTpcBVapZWqylLppxOAEV+BB4JapOqQDTkn9xYJ6L8pIScPg6TBOVwLsgABwbSEhiCyzmiHDikNlP7GQkARxd8AV0OxIHovAAtFA4GEwoTQrmMKEFfQlfR3Z7ZVgMIz8MzIeV6U68xakKqPSy3oII4wo0g3JCRPQMHZ6QBhLTKlBQaAWyH8WUAFQD2JHnvYzIAkokEFSwKGYQBBRKUmAKE6tlklmBvyGMCBgL9Q-gYBwQC3DfZRlCAA)

[parser: typescript](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKBLAtgBwgJxgAJgiA1OMGAgGiIEMATRuxjANw0bjoGcBXAEYx89KnSz8ANjAw4pATyIBfIgDN8ELEQDkAOgD07StXw702PIRJEp2DMVUatuwwCZG5qBdwFipLHocOnw4Rn4wOBV1TW0dfihufF5IUK90dDgADytiSChePIgACzheDGhUGABeIgAKNQJIpHITAgBKImqAPnrG-EjeFooqAgBtAF1OnoyRMIi4BqayuiYWIgAGdtmAH162Tm46qQQAcxhizoMDIgOuKMElC6jqGHopIih+LEE4fCIIGp1MteBkoCAaCAIDhZNBeMhQPR8JoAO4ABSRCHhKHo7AgXAhIEEojAAGs4DAAMo4MQYKCnZAifg8EDFGBYKQAdWKDjKNMilKxDg4DgUyHAvHhkLpvD+MDRolOgWQanesshACteFkAEIk8lU+hYOAAGTpcBVapZWqylLppxOAEV+BB4JapOqQDTkn9xTAFDgymB8HIYIScCHYJyuBdkAAODaQiMQWWc0Q4cURsp-YyEgCOLvgCuh2JA9F4AFooHAwmFCaECxhQgr6Er6O7PbKsBhGfhmZDyvSnYWLUhVR6WW9BNHGLGkG5ISJ6Bg7PSAMJaZUoKDQC2Q-iygAq9EE2PHnvYzIAkokEFTg6GAIKJSn+k4dlnlsNjq2QxgQMAP0hCB+BgHBQLcD9lGUIA)

This adds a option `typescript-babel-parser` which will use babel instead of typescript. 

Note: I have not tested but this is the functionality I need.

### CODE REVIEW

**Comment by jonlabelle** [comment]
Hi @rockerBOO. Can you address the [build errors](https://travis-ci.org/jonlabelle/SublimeJsPrettier/builds/633572621?utm_medium=notification&utm_source=github_status) please... looks like it's just a spacing issue.

**Comment by jonlabelle** [comment]
Hi @rockerBOO. Did a little digging, and it looks like there's already an open [PR](https://github.com/prettier/prettier/pull/6400) for the babel-typescript parser... and w/ quite a discussion in progress. Therefore, I'm going to defer this PR.

In the meantime, a work around would be to create a prettier config file, and add your [preferred parser](https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option) for the specific file type.

**Comment by rockerBOO** [comment]
I tried the prettier override option, but it seems to still use the typescript parser. Is this working as expected?

[example code](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKkoGcYAICGAJobgLwFkB8uARlRQNS3qY65YCuNMATvmHnL56dUtWEBaZlHRFCACgCMASnkAmZbnQAfap258B65enQgANCAgAHGAEtoWZKHw8eEAO4AFVwicp8ADcIO0ILEBpDAGs4GABla347KABzZF4OOEsACxgAWwAbAHVsu3gsRLA4OL8yu0CygE9kcCwnS2SsOB4YLz4UvPxkADN8Aq7LACssAA8AIWjYuPw8uAAZZLgRsYmQaZm45JSCuABFDgh4bfGskESeLp4WmnwaOALw6x5kmCLQmGyyAAHAAGSxfCBdIp8awtL5wR6BLaWACOF3gfRs-hA+CwEigcDghCJ4R4cDRdjJfXwAyGSFGN0sXTydnSPEyTKOJ3Oly29J2txgrz+hAByDUll4+DsBSOAGEIHlBi0oNBkSAOF0ACqvfwM3aBTIASSgxNgcTA31sAEFTXEYI0TtcugBfF1AA)

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

[debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":true,"parser":"typescript","stdin-filepath":"C:\\projects\\vector-forces\\src\\lib\\forces\\test.ts","loglevel":"debug","config":"C:\\projects\\vector-forces/.prettierrc","cursor-offset":88,"plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] load config file from 'C:\projects\vector-forces/.prettierrc'
[debug] loaded options `{"semi":false,"singleQuote":true,"useTabs":true,"parser":"babel"}`
[debug] applied config-precedence (cli-override): {"filepath":"C:\\projects\\vector-forces\\src\\lib\\forces\\test.ts","cursorOffset":88,"parser":"typescript","semi":false,"singleQuote":true,"useTabs":true}
[error] src\lib\forces\test.ts: SyntaxError: Expression expected. (6:2)
[error]   4 | 
[error]   5 | add(1)(2) 
[error] > 6 | |> subtract(2)
[error]     |  ^
[error]   7 | 
[error]   8 | 


Prettier process finished with exit code 2.
```

### `.prettierrc`
```json
{
	"semi": false,
	"singleQuote": true,
	"useTabs": true,
	"overrides": [
		{
      "files": "*.ts",
      "options": {
        "parser": "babel"
      }
    }
	]
}
```

```json
{
	"debug": true,
	"auto_format_on_save": false,
	"prettier_options": {
		"semi": false,
		"singleQuote": true
	},
	"additional_cli_args": {
		"--config": "${project_path}/.prettierrc"
	}
}
```

**Comment by rockerBOO** [comment]
Maybe an option can be added to disable parser cli-override and use the prettier option implied parser.

**Comment by jonlabelle** [comment]
[That's it](https://prettier.io/docs/en/cli.html#--config-precedence)... add an entry to `additional_cli_args` for `--config-precedence` with a value of `file-override`.

**Comment by rockerBOO** [comment]
That did it! Thanks!

**Pull request closed without merging**
