### PR TITLE
Use correct working directory so Prettier is able to find plugins

### PR DESCRIPTION
**Pull request by jakubmazanec**
If Prettier installed in the Sublime project is used, the working directory must be set up so Prettier can find plugins. We can assume the plugins will be in the same `node_modules` directory.

### CODE REVIEW

**Comment by jonlabelle** [comment]
Still pukes...

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/.bin/prettier --config /Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/prettier.config.js --parser typescript --use-tabs true --stdin-filepath /Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/src/main.ts --log-level debug

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

[debug] normalized argv: {"":[],"cache":false,"color":true,"editorconfig":true,"useTabs":true,"config":"/Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/prettier.config.js","parser":"typescript","filepath":"/Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/src/main.ts","logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":[],"__raw":{"_":[],"cache":false,"color":true,"editorconfig":true,"use-tabs":true,"config":"/Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/prettier.config.js","parser":"typescript","stdin-filepath":"/Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/src/main.ts","log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] load config file from '/Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/prettier.config.js'
[debug] loaded options `{"useTabs":false,"tabWidth":2,"endOfLine":"lf","arrowParens":"always","bracketSameLine":false,"bracketSpacing":false,"embeddedLanguageFormatting":"auto","htmlWhitespaceSensitivity":"css","jsxSingleQuote":false,"printWidth":100,"proseWrap":"always","quoteProps":"as-needed","requirePragma":false,"semi":true,"singleQuote":true,"trailingComma":"all","plugins":["prettier-plugin-packagejson"]}`
[error] /Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/src/main.ts: Error: Cannot find package 'prettier-plugin-packagejson' imported from /Users/jon/Downloads/SublimeJsPrettier-bug/noop.js
[error]     at new NodeError (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:18797:5)
[error]     at packageResolve (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19742:9)
[error]     at moduleResolve (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19774:20)
[error]     at defaultResolve (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19879:15)
[error]     at resolve (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19897:12)
[error]     at importFromFile (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19912:15)
[error]     at importFromDirectory (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:20181:10)
[error]     at file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:20198:12
[error]     at async loadPlugin (file:///Users/jon/Downloads/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:20203:28)
[error]     at async Promise.all (index 0)


Prettier process finished with exit code 2.
```

**Comment by jakubmazanec** [comment]
Are you sure you're running the updated code? This looks exactly like the original issue error. I updated the PR and added logging.

> It also breaks resolution of Prettier when installed globally.

Does it? I thought that the condition `st_project_path in prettier_cli_path` would ensure that the working directory is changed only when the Prettier CLI is located within a subdirectory of the Sublime project.

**Comment by jonlabelle** [comment]
@jakubmazanec, would the *correct* working directory be the `node_modules/` directory, or the `node_modules/.bin/` directory?

**Comment by jonlabelle** [comment]
Thanks @jakubmazanec!

**Comment by jakubmazanec** [comment]
> @jakubmazanec, would the _correct_ working directory be the `node_modules/` directory, or the `node_modules/.bin/` directory?

`node_modules` must be reachable from the working directory using Node resolution algorithm, so the problem arises only when the CWD is  in the tree structure above the directory containing `node_modules`.

**Pull request merged**
