### PR TITLE
[feature] when using context, .prettierignore is skipped

### PR DESCRIPTION
**Pull request by kud**
ref: https://github.com/jonlabelle/SublimeJsPrettier/issues/210

### CODE REVIEW

**Comment by kud** [comment]
What do you need from me about "feedback"? :)

**Comment by jonlabelle** [comment]
Have you tried [this option](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L151)?

**Comment by kud** [comment]
Yes and apparently it still keeps in mind the "ignore" file. :/

**Comment by jonlabelle** [comment]
@kud: Try adding your jinja2/nunjucks files to [auto_format_on_save_excludes](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L101).

**Comment by kud** [comment]
I can't do that IMO because my files are in .html. :/

I could maybe add an absolute path however but I can't exclude all .html files.

**Comment by jonlabelle** [comment]
I'm going to pass on this PR for now; but may revisit in the future.

**Pull request closed without merging**
